FROM ubuntu:18.04

# Install Python
RUN apt-get update && \
    apt-get install software-properties-common -y && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
    python3.9 python3-pip python3.9-dev

# Copy Flask Server from local directory into the image
WORKDIR flask-app-server/
COPY ./flask-app-server/ .

# Install required python libraries
RUN pip3 install -U pip setuptools 
RUN pip3 install -r requirements.txt
