FROM ubuntu:18.04
RUN apt-get update && \
    apt-get install wget libcurl4 openssl liblzma5 -y 

# MongoDB Timeseries Database Installation 
RUN wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-latest.tgz 
RUN tar -xvf mongodb-linux-x86_64-ubuntu1804-latest.tgz -C /tmp
RUN mv /tmp/mongo*/ /tmp/mongo_executables/
RUN mv /tmp/mongo_executables/ ~/

# MongoDB Data Folder creation
RUN mkdir /tmp/mongodbdata
COPY ./db-scripts/init.js  /tmp/init.js

EXPOSE 9123
